// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Used by the Prisma CLI (migrate, studio, etc). Runtime queries use the
    // driver adapter in src/lib/prisma.ts instead.
    url: env("DIRECT_URL"),
  },
});
