// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
// Match Next.js's own env precedence: .env.local (real secrets, git-ignored)
// wins over .env (placeholder fallback). dotenv's config() won't override a
// var that's already set, so load .env.local first.
config({ path: ".env.local" });
config({ path: ".env" });
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Used by the Prisma CLI (migrate, studio, etc). Runtime queries use the
    // driver adapter in src/lib/prisma.ts instead.
    url: env("DIRECT_URL"),
  },
});
